# Site settings
title:          Consumer Protection Council
shortname:      CPC
company:        Consumer Protection Council
description:    >-
  Protecting and enhancing consumer's interest through information, education and enforcement of appropriate standards for goods and services.
url:            'http://cpc.softcom.ng'
charset:        'UTF-8'
timezone:       Africa/Lagos


# Headquarters
headquarters:
  title:    'Headquarters'
  address:  '17 Nile Street, Maitama, Abuja, FCT'
  phone:    '0805 600 2020, 0805 600 3030'
  email:    'contact@cpc.gov.ng'


# Social Media Handles
social_media:
  twitter:    cpcnig
  facebook:   cpcng
  instagram:  cpcnigeria


# Included Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate


# Build settings
markdown:       kramdown
permalink:      pretty


# Collections
collections:
  uploads:
    title:  Uploads
    output: true
  testimonials:
    title:  Testimonials
    output: true
  locations:
    title:  Contact
    output: true
  directors:
    title:  Directors
    output: true
  faqs:
    title:  FAQs
    output: true
  departments:
    title:  Departments
    output: true
  downloads:
    title:  Downloads
    output: true
  gallery:
    title:  CPC Media Gallery
    output: true
    permalink: /:collection/:name
  consumer_blog:
    title: Consumer Blog
    output: true
  news:
    title: News
    output: true
  how-to:
    title: How To
    output: true

# Defaults
defaults:
  - scope:
      path: 'testimonials'
      type: testimonials
    values:
      permalink: '/testimonials/'
      layout: default
  - scope:
      path: 'directors'
      type: directors
    values:
      permalink: '/directors/'
      layout: director
  - scope:
      path: 'contact'
      type: contact
    values:
      permalink: '/contact/'
      layout: contact
  - scope:
      path: 'departments'
      type: departments
    values:
      permalink: '/departments/'
      layout: departments
  - scope:
      path: 'docs'
      type: docs
    values:
      permalink: '/docs/'
      layout: docs
  - scope:
      path: 'faqs'
      type: faqs
    values:
      permalink: '/faqs/'
      layout: faqs
  - scope:
      path: 'uploads'
      type: uploads
    values:
      permalink: '/uploads/'
      layout: uploads
  - scope:
      path: 'media'
      type: media
    values:
      permalink: '/media/'
      layout: media
  - scope:
      path: 'consumer-blog'
      type: consumer-blog
    values:
      permalink: '/:collection/:name'
      layout: post
  - scope:
      path: 'news'
      type: news
    values:
      permalink: '/:collection/:name'
      layout: post
  - scope:
      path: 'how-to'
      type: how-to
    values:
      permalink: '/:collection/:name'
      layout: post


# Include
include:
  - _pages


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - dev
  - .gitignore